### ISSUE TITLE
Example in JS

### ISSUE THREAD

**Issue by Candoyeya** [deepbass/bolt-azure-functions-receiver#2]
Good day.

Could you support with an example of use with javascript, so far, this is the only package oh example that I have found to work with bolt and azure.

But I don't know if it causes problems or is compatible with javascript.

**Comment by deepbass** [comment]
Hi sorry this very very late - I'm quite new to having an open source library! 

Happy to add an example, but basically it will work just the same in javascript. Anywhere you see a : followed by a type you can remove and it should just work.

**Comment by deepbass** [comment]
I've now pushed v 0.0.4 that updates the docs to show a JS use case
